#!/usr/bin/env bash
# Typecheck every module through a single root-level entry.
# See docs/MODULES.md for why the entry has to be at the root.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

entry="$root/.check-all.bend"
{
  echo "# Generated by tools/check.sh. Do not edit."
  echo "import Base"
  i=0
  while IFS= read -r f; do
    i=$((i+1))
    echo "import ./$f as M$i"
  done < <(find core spec closure query execute index adapters host cli proofs \
             -name '*.bend' 2>/dev/null | sort)
  echo "def main() -> Nat:"
  echo "  0n"
} > "$entry"

trap 'rm -f "$entry"' EXIT
"$root/tools/bend" "$entry" --check-only
